version: '3.8'
services:
  server:
    build:
      context: .
    container_name: server
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db
    command: npm start
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/mysql
volumes:
  postgres:
